#!/bin/bash
#
# Script to assemble all Address chapter individual curated notes in a single md file
#

cat "Addressing/Packet Format.md"           >  Addressing.md
cat "Addressing/Protocol Demultiplexing.md" >> Addressing.md
cat "Addressing/ARP.md" 		              >> Addressing.md

# Replace Pictures directory (running at root dir)
sed -i -e 's~../pictures~pictures~g' Addressing.md

