#!/bin/bash
#
# Script to assemble all Address chapter individual curated notes in a single md file
#

cat "Addressing/Packet Format.md"           >  Address_Book.md
cat "Addressing/Protocol Demultiplexing.md" >> Address_Book.md
cat "Addressing/ARP.md" 		              >> Address_Book.md

# Replace Pictures directory (running at root dir)
sed -i -e 's~../pictures~pictures~g' Address_Book.md

