#!/bin/bash
#
# Script to assemble all Media Access subchapters into a single chapter md file
#

chapter_name="Bridging.md"
folder_name="Bridging"

cat "$folder_name/Hubs_vs_Switches"          >  $chapter_name
cat "$folder_name/Routers_and_Bridges.md"    >> $chapter_name
cat "$folder_name/VLANs.md"                  >> $chapter_name
cat "$folder_name/Spanning Trees.md"         >> $chapter_name
cat "$folder_name/IEEE802_1D.md"             >> $chapter_name
cat "$folder_name/Gigabit Ethernet.md"       >> $chapter_name
cat "$folder_name/LLC.md"                    >> $chapter_name

# Replace Pictures directory (running at root dir)
sed -i -e 's~../pictures~pictures~g' $chapter_name

